export const PARTICIPANT_DATA;
export const THEME_CHANGED;
export const SORT_PARTICIPANTS;

export const communicationType = {
  ALL_DISCOVERED: 'ALL_DISCOVERED',
  PARTICIPANT_PAYLOAD: 'PARTICIPANT_PAYLOAD',
  SETUP_COMM: 'SETUP_COMM',
}
