module.exports = {
  communicationType: {
    ALL_DISCOVERED: 'ALL_DISCOVERED',
    PARTICIPANT_PAYLOAD: 'PARTICIPANT_PAYLOAD',
    SETUP_COMM: 'SETUP_COMM',
    MESSAGE_TEXT: 'MESSAGE_TEXT',
  },
};
